name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Change server to production
        run: ./change_server.sh

      - name: test
        run: cat ./src/config.json

